<?php
/**
 * Created by PhpStorm.
 * User: ql-qf
 * Date: 2018/1/5
 * Time: 9:06
 */


/**
 * Class Name: wp_bootstrap_navwalker
 * GitHub URI: https://github.com/twittem/wp-bootstrap-navwalker
 * Description: A custom WordPress nav walker class to implement the Bootstrap 3 navigation style in a custom theme using the WordPress built in menu manager.
 * Version: 2.0.4
 * Author: Edward McIntyre - @twittem
 * License: GPL-2.0+
 * License URI: http://www.gnu.org/licenses/gpl-2.0.txt
 */
add_action( 'init', 'register_my_menu' );
function register_my_menu() {
	register_nav_menus( array(
		'top_menu'    => '默认菜单',
		'footer_menu' => '底部菜单',
		'mobile_menu' => '手机菜单'
	) );
}


class gemsky_topmenu_walker extends Walker_Nav_Menu {


	function start_el( &$output, $item, $depth = 0, $args = array(), $id = 0 ) {
		if($depth == 0 || true){
			if($item->current){
				$output .= "<li class='menu-item  active'><a href='". $item->url ."' class='active'>". $item->title ."</a>";
			}
			else{
				$output .= "<li class='menu-item'><a href='". $item->url ."'>". $item->title ."</a>";

			}

		}
//		else{
//			$output .= "<li class='menu-item'>";
//		}

	}
	function end_el( &$output, $item, $depth = 0, $args = array(), $id = 0 ) {
		$output .= "</li>";
	}

	function start_lvl( &$output, $depth = 0, $args = array() ) {

		$output .= "<ul class='sub-menu'>";
	}
	function end_lvl( &$output, $depth = 0, $args = array() ) {
		parent::end_lvl( $output, $depth, $args ); // TODO: Change the autogenerated stub
	}


}

class gemsky_mobilemenu_walker extends Walker_Nav_Menu{
	function start_el( &$output, $item, $depth = 0, $args = array(), $id = 0 ) {
		if($depth == 0 || true){
			if($item->current){
				$output .= "<li class='title  active'><i class='dropdown icon'></i><a href='". $item->url ."' class='active'>". $item->title ."</a>";
			}
			else{
				$output .= "<li class='title'><a href='". $item->url ."'>". $item->title ."</a>";

			}

		}
//		else{
//			$output .= "<li class='menu-item'>";
//		}

	}
	function end_el( &$output, $item, $depth = 0, $args = array(), $id = 0 ) {
		$output .= "</li>";
	}

	function start_lvl( &$output, $depth = 0, $args = array() ) {

		$output .= "<ul class='sub-menu'>";
	}
	function end_lvl( &$output, $depth = 0, $args = array() ) {
		parent::end_lvl( $output, $depth, $args ); // TODO: Change the autogenerated stub
	}
}